openapi: 3.0.1
info:
  title: Rest API Docs
  description: MetaNews is a news site
  version: 1.0.0
paths:
  /users/:
    $ref: 'users.yaml#/paths/~1users~1'
  /users/{id}:
    $ref: 'users.yaml#/paths/~1users~1{id}'
  /users/me:
    $ref: 'users.yaml#/paths/~1users~1me'
  /users/login/:
    $ref: 'users.yaml#/paths/~1users~1login~1'
  /authors/:
    $ref: 'authors.yaml#/paths/~1authors~1'
  /authors/{id}:
    $ref: 'authors.yaml#/paths/~1authors~1{id}'
  /posts/full/:
    $ref: 'news.yaml#/paths/~1posts~1full~1'
  /posts/:
    $ref: 'news.yaml#/paths/~1posts~1'
  /posts/full/{id}:
    $ref: 'news.yaml#/paths/~1posts~1full~1{id}'
  /posts/{id}:
    $ref: 'news.yaml#/paths/~1posts~1{id}'
  /drafts/full/:
    $ref: 'drafts.yaml#/paths/~1drafts~1full~1'
  /drafts/:
    $ref: 'drafts.yaml#/paths/~1drafts~1'
  /drafts/full/{id}:
    $ref: 'drafts.yaml#/paths/~1drafts~1full~1{id}'
  /drafts/{id}:
    $ref: 'drafts.yaml#/paths/~1drafts~1{id}'
  /drafts/publish/{id}:
      $ref: 'drafts.yaml#/paths/~1drafts~1publish~1{id}'
  /comments/news/{id}:
    $ref: 'comments.yaml#/paths/~1comments~1news~1{id}'
  /comments/:
    $ref: 'comments.yaml#/paths/~1comments~1'
  /comments/{id}:
    $ref: 'comments.yaml#/paths/~1comments~1{id}'
  /categories/:
    $ref: 'categories.yaml#/paths/~1categories~1'
  /categories/{id}:
    $ref: 'categories.yaml#/paths/~1categories~1{id}'
  /tags/:
    $ref: 'tags.yaml#/paths/~1tags~1'
  /tags/{id}:
    $ref: 'tags.yaml#/paths/~1tags~1{id}'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt