openapi: 3.0.1
info:
  title: NewSite Rest API
  description: News
  version: 1.0.0
paths:
  /posts/:
    get:
      tags:
        - News
      summary: All available news
      parameters:
        - in: query
          name: categoryId
          required: false
          schema:
            type: number
        - in: query
          name: authorName
          required: false
          schema:
            type: string
        - in: query
          name: title
          required: false
          schema:
            type: string
        - in: query
          name: content
          required: false
          schema:
            type: string

        - in: query
          name: tag
          required: false
          schema:
            type: number
        - in: query
          name: tags__in
          required: false
          schema:
            type: array
            items: 
              type: number
        - in: query
          name: tags__all
          required: false
          schema:
            type: array
            items: 
              type: number

        - in: query
          name: created_at
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: created_at__lt
          required: false
          schema:
            type: string
            format: date # express-openapi-validator fail validation
        - in: query
          name: created_at__gt
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: searchText
          required: false
          schema:
            type: string
      
        - in: query
          name: by
          required: false
          schema:
            type: string
            enum: [date, author, category, photoCount]
        - in: query
          name: direction
          required: false
          schema:
            type: string
            enum: [asc, desc]
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            example: 5
          description: The numbers of items to return
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            example: 0
          description: The number of items to skip before starting to collect the result set

      responses:
        200:
          description: A list of news.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "difinitions.yaml#/components/schemas/FullNews"

  /posts/{id}:
    get:
      tags:
        - News
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
          description: Numeric ID of the news to get
      responses:
        200:
          description: One post.
          content:
            application/json:
              schema:
               $ref: "difinitions.yaml#/components/schemas/FullNews"

  /posts/raw/:
    get:
      tags:
        - News
      summary: All available news (available only for admins)
      security:
        - cookieAuth: []
      parameters:
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            example: 0
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            example: 5
          description: The numbers of items to return
      responses:
        200:
          description: A list of news.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "difinitions.yaml#/components/schemas/News"

  /posts/drafts/:
    get:
      tags:
        - News
      summary: my drafts
      security:
        - cookieAuth: []
      parameters:
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            example: 0
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            example: 5
          description: The numbers of items to return
      responses:
        200:
          description: A list of news.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "difinitions.yaml#/components/schemas/News"

    post:
      tags:
        - News
      summary: Add a new News
      security:
        - cookieAuth: []
      requestBody:
        description: News create request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/CreateNews"
        required: true
      responses:
        201:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "difinitions.yaml#/components/schemas/News"

    patch:
      tags:
        - News
      summary: Update News
      security:
        - cookieAuth: []
      requestBody:
        description: News update request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/News"
        required: true
      responses:
        200:
          description: Successful operation

  /posts/drafts/{id}:
    delete:
      security:
        - cookieAuth: []
      tags:
        - News
      summary: Delete News (available only for admins)
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: integer
          description: News delete request
      responses:
        200:
          description: Successful operation

  /posts/drafts/publish/{id}:
    get:
      security:
        - cookieAuth: []
      tags:
        - News
      summary: publish News (available only for author)
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: integer
          description: News publish request
      responses:
        200:
          description: Successful operation
