openapi: 3.0.1
info:
  title: NewSite Rest API
  description: Tags
  version: 1.0.0
paths:
  /tags/:
    get:
      tags:
        - Tags
      summary: All available tags
      parameters:
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            example: 0
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          required: true
          schema:
            type: integer
            example: 5
          description: The numbers of items to return
      responses:
        200:
          description: A list of tags.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "difinitions.yaml#/components/schemas/Tag"
        500:
          description: Unexpected Error
    post:
      tags:
        - Tags
      summary: Add a new Tag (available only for admins)
      security:
        - cookieAuth: []
      requestBody:
        description: Tag create request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/CreateTag"
        required: true
      responses:
        201:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "difinitions.yaml#/components/schemas/Tag"
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error
    patch:
      tags:
        - Tags
      summary: Update Tag (available only for admins)
      security:
        - cookieAuth: []
      requestBody:
        description: Tag update request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/Tag"
        required: true
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error

  /tags/{id}:
    delete:
      security:
        - cookieAuth: []
      tags:
        - Tags
      summary: Delete Tag (available only for admins)
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: integer
          description: Tag delete request
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid request provided
        500:
          description: Unexpected Error